sudo: required
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true react-test npm run test

after_success:
  - docker build -t ohanlokb/multi-client ./client
  - docker build -t ohanlokb/multi-nginx ./nginx
  - docker build -t ohanlokb/multi-server ./server
  - docker build -t ohanlokb/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ohanlokb/multi-client
  - docker push ohanlokb/multi-nginx
  - docker push ohanlokb/multi-server
  - docker push ohanlokb/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-679345455551"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY